language: python
python:
- '3.7'

notifications:
  email:
    on_success: never
    on_failure: always

install: pip install -r requirements.txt

before_script: pip install -r requirements-test.txt

script: pytest tests

before_deploy:
- pip install m2r
- python3 setup.py sdist bdist_wheel
